# Generated by Django 5.2.9 on 2026-03-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_dob_user_emergency_contact_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
