# Generated by Django 5.2.9 on 2026-04-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
