# Generated by Django 5.2.9 on 2026-04-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_issue_date_user_license_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
