# Generated by Django 5.2.9 on 2026-04-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
