# Generated by Django 5.2.9 on 2026-03-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_id_trip_trip_id_alter_trip_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='alert_helpful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
